# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: black
        name: black
        language: system
        entry: black
        args: ["--check"]
        types: [python]
    -   id: isort
        name: isort
        language: system
        entry: isort
        args: ["--check", "--diff", "--color"]
        types: [python]
    -   id: flake8
        name: flake8
        language: system
        entry: flake8
        types: [python]
        exclude: "migrations"
    -   id: mypy
        name: mypy
        language: system
        entry: mypy
        types: [python]
